/**
 * Tune Moon — sound system.
 *
 * Moon is the last Tune, and the one people speak. It has 27 sounds.
 *
 *   vowels          i e a o u
 *   nasals          m n q
 *   voiced stops    b d g
 *   voiceless stops p t k
 *   breath          h
 *   alveolar rub    s z
 *   labial rub      f v
 *   palatal rub     x j
 *   dental rub      c C
 *   glides          w l r y
 *
 * Moon is Rock spoken quickly. The stress settled on the first
 * syllable, unstressed vowels dropped out, and the consonants that
 * ended up beside each other stayed there. That is where every cluster
 * comes from, and it is why Moon is short.
 *
 *   Rock  bat.mis   ->   Moon  batmis, batmis -> batmis
 *   Rock  bat.mis   ->   Moon  batms  -> batms, then batems
 *
 * Eight shapes survived:
 *
 *   one syllable    CVC   CVCC   CCVC   CCVCC
 *   two syllables   CVCVC   CVCCVC   CCVCVC   CVCVCC
 *
 * Moon is hand tuned. Rock is generated by rule and Tree is generated
 * by rule, but Moon is a lexicon people built, and it is kept in
 * `tune.csv` at the root of the package. This module says what Moon's
 * shapes are so that lexicon can be checked against them.
 */

// ─── Inventory ──────────────────────────────────────────

export const VOWELS = ['i', 'e', 'a', 'o', 'u']

export const NASALS = ['m', 'n', 'q']
export const VOICED_STOPS = ['b', 'd', 'g']
export const VOICELESS_STOPS = ['p', 't', 'k']
export const BREATH = ['h']
export const ALVEOLAR_RUB = ['s', 'z']
export const LABIAL_RUB = ['f', 'v']
export const PALATAL_RUB = ['x', 'j']
export const DENTAL_RUB = ['c', 'C']
export const GLIDES = ['w', 'l', 'r', 'y']

export const CONSONANTS = [
  ...NASALS,
  ...VOICED_STOPS,
  ...VOICELESS_STOPS,
  ...BREATH,
  ...ALVEOLAR_RUB,
  ...LABIAL_RUB,
  ...PALATAL_RUB,
  ...DENTAL_RUB,
  ...GLIDES,
]

export const SOUNDS = [...VOWELS, ...CONSONANTS]

export const RUBS = [
  ...ALVEOLAR_RUB,
  ...LABIAL_RUB,
  ...PALATAL_RUB,
  ...DENTAL_RUB,
]

// ─── Roles ──────────────────────────────────────────────

/**
 * Moon has five roles. Rock had three. The two extra ones came from
 * the two Rock vowels that split.
 *
 *   Rock -i action   ->   Moon -i action, -e relation
 *   Rock -u feature  ->   Moon -u feature, -o operator
 *
 * The bare root works as a modifier, which is the feature form worn
 * down one step further because a modifier is never stressed.
 */
export const ROLES: Array<{ name: string; vowel: string; note: string }> = [
  { name: 'entity', vowel: 'a', note: 'what exists' },
  { name: 'action', vowel: 'i', note: 'what happens' },
  { name: 'feature', vowel: 'u', note: 'what something is like' },
  { name: 'relation', vowel: 'e', note: 'how things connect' },
  { name: 'operator', vowel: 'o', note: 'how meaning is controlled' },
]

// ─── Shapes ─────────────────────────────────────────────

/**
 * The eight shapes Moon allows. Stress falls on the first syllable of
 * every one of them.
 */
export const SHAPES = [
  'CVC',
  'CVCC',
  'CCVC',
  'CCVCC',
  'CVCVC',
  'CVCCVC',
  'CCVCVC',
  'CVCVCC',
]

export const SHAPE_SET = new Set(SHAPES)

// ─── Sort Order ─────────────────────────────────────────

export const CHAR_ORDER =
  'i e a o u m n q b d g p t k h s z f v x j c C w l r y'.split(' ')

export const CHAR_RANK = new Map(CHAR_ORDER.map((c, i) => [c, i]))

export function compareWords(a: string, b: string): number {
  const len = Math.max(a.length, b.length)
  for (let i = 0; i < len; i++) {
    const ra = CHAR_RANK.get(a[i]) ?? 99
    const rb = CHAR_RANK.get(b[i]) ?? 99
    if (ra !== rb) {
      return ra - rb
    }
  }
  return 0
}

// ─── Shape ──────────────────────────────────────────────

export function isVowel(ch: string): boolean {
  return VOWELS.includes(ch)
}

export function isConsonant(ch: string): boolean {
  return CONSONANTS.includes(ch)
}

/** `bat` becomes `CVC`, `stulatx` becomes `CCVCVCC`. */
export function toShape(word: string): string | null {
  let shape = ''
  for (const sound of word) {
    if (isVowel(sound)) {
      shape += 'V'
    } else if (isConsonant(sound)) {
      shape += 'C'
    } else {
      return null
    }
  }
  return shape
}

export function countSyllables(shape: string): number {
  return [...shape].filter(s => s === 'V').length
}

export function isMoonShape(word: string): boolean {
  const shape = toShape(word)
  return shape !== null && SHAPE_SET.has(shape)
}

// ─── Syllable Rules ─────────────────────────────────────

/**
 * Rhymes Moon will not say. A close front vowel followed by a liquid
 * blurs into the liquid, so `bil` and `ber` are not words Moon can
 * hold apart from `bi` and `be`.
 */
export const BAD_RHYME = ['il', 'el', 'ir', 'er']

/** Sounds too weak to close a syllable. They need a vowel after them. */
export const BAD_CLOSE = ['y', 'h', 'w']

/** Sounds that cannot open a syllable. */
export const BAD_OPEN = ['q']

export type SyllableRule = {
  name: string
  note: string
  test: (syllable: string) => boolean
}

export const SYLLABLE_RULES: Array<SyllableRule> = [
  {
    name: 'no-weak-close',
    note: 'a syllable never ends in y, h or w',
    test: syllable => !BAD_CLOSE.includes(syllable[syllable.length - 1]),
  },
  {
    name: 'no-back-open',
    note: 'a syllable never starts with q',
    test: syllable => !BAD_OPEN.includes(syllable[0]),
  },
  {
    name: 'no-blurred-rhyme',
    note: 'a syllable never ends in il, el, ir or er',
    test: syllable => !BAD_RHYME.includes(syllable.slice(-2)),
  },
]

export function testSyllable(syllable: string): {
  ok: boolean
  broke: Array<string>
} {
  const broke = SYLLABLE_RULES.filter(r => !r.test(syllable)).map(r => r.name)
  return { ok: broke.length === 0, broke }
}

/** Runs the syllable rules over every syllable of a word. */
export function testSounding(word: string): {
  ok: boolean
  broke: Array<string>
} {
  const broke = new Set<string>()
  for (const syllable of toSyllables(word)) {
    for (const name of testSyllable(syllable).broke) {
      broke.add(name)
    }
  }
  return { ok: broke.size === 0, broke: [...broke] }
}

/** Where a word breaks into syllables, with the stress on the first. */
export function toSyllables(word: string): Array<string> {
  const shape = toShape(word)
  if (!shape) {
    return [word]
  }
  /** A cluster in the middle splits down the middle, so `batmis` is
   * `bat` and `mis`, not `ba` and `tmis`. */
  const parts: Array<string> = []
  let current = ''
  let seenVowel = false
  for (let i = 0; i < word.length; i++) {
    const sound = word[i]
    if (isVowel(sound)) {
      if (seenVowel) {
        parts.push(current.slice(0, -1))
        current = current.slice(-1)
      }
      seenVowel = true
    }
    current += sound
  }
  parts.push(current)
  return parts.filter(p => p.length > 0)
}
